name: build
on: push

jobs:
  # generate zip
  build-livy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Maven
        run: |
          sudo add-apt-repository 'deb https://cloud.r-project.org/bin/linux/ubuntu xenial-cran35/'
          sudo apt-get update
          sudo apt-get -qq --allow-unauthenticated install r-base
          sudo apt-get -qq install python3-pip python-dev
          sudo apt-get -qq install libkrb5-dev
          sudo apt-get -qq remove python-setuptools
          sudo pip2 -q install --upgrade "pip < 10.0.0" "setuptools < 36"
          sudo python3 -m pip -q install --upgrade "pip < 10.0.0" "setuptools < 36"
          sudo pip2 -q install codecov cloudpickle
          sudo python3 -m pip -q install cloudpickle
          sudo pip2 -q install "requests >= 2.10.0" pytest flaky flake8 requests-kerberos
          sudo pip3 -q install "requests >= 2.10.0" pytest flaky requests-kerberos
          mvn -Pthriftserver -DskipTests -Dmaven.javadoc.skip=true -B -V -e verify

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Maven
        run: mvn package -DskipTests -Dmaven.javadoc.skip=true -B -V -e
