name: build
on:
  push:
    tags:
      - 'v*'

jobs:
  # generate zip
  build-livy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Show versions
        run: |
          which pip2
          which pip3
          which python
          which python2
          which python3
          python -V
          cat /etc/os-release

      - name: Build with Maven
        run: |
          sudo add-apt-repository 'deb https://cloud.r-project.org/bin/linux/ubuntu xenial-cran35/'
          sudo apt-get update
          sudo apt-get upgrade -y
          sudo apt-get -qq --allow-unauthenticated install r-base
          sudo apt-get -qq install python3-pip python-dev
          sudo apt-get -qq install libkrb5-dev
          sudo apt-get -qq remove python-setuptools

          sudo pip2 -q install --upgrade "pip < 10.0.0" "setuptools < 36"
          sudo pip2 -q install codecov cloudpickle
          sudo pip2 -q install "requests >= 2.10.0" pytest flaky flake8 requests-kerberos

          mvn package -Pthriftserver -DskipTests -Dmaven.javadoc.skip=true -B -V -e

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: assembly/target/apache-livy-0.8.0-incubating-SNAPSHOT-bin.zip
          asset_name: apache-livy-0.8.0-incubating-SNAPSHOT-bin.zip
          asset_content_type: application/zip

      - name: Show files
        run: |
          mkdir hoge
          unzip assembly/target/apache-livy-0.8.0-incubating-SNAPSHOT-bin.zip -d hoge
          sudo apt-get install -y tree
          tree hoge

